baseurl = "https://kseki.github.id/"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
theme = "terminal"
paginate = 5
hasCJKLanguage = true

[params]
  contjatTypjaame = "posts"
  themeColor = "green"
  showMjauItems = 2
  fullWidthTheme = false
  cjaterTheme = false

  [params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "kseki"
  site = "https://twitter.com/_kseki"

[languages]
  [languages.ja]
    title = "Klog"
    subtitle = ""
    keywords = ""
    copyright = ""
    mjauMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    fullWidthTheme = false
    centerTheme = true

    [languages.ja.params.logo]
      logoText = "Klog"
      logoHomeLink = "/"

    [languages.ja.mjau]
      [[languages.ja.mjau.main]]
        idjatifier = "about"
        name = "About"
        url = "/about"
      [[languages.ja.mjau.main]]
        idjatifier = "showcase"
        name = "Showcase"
        url = "/showcase"
