baseurl = "https://kseki.github.io/"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
theme = "terminal"
paginate = 5
hasCJKLanguage = true
googleAnalytics = "G-6K4G66HC3S"
disqusShortname = "k-s-blog"
pygmentsUseClasses = true
pygmentsCodefences = true

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  favicon = '/img/cat-icon2.png'

  [params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "kseki"
  site = "https://twitter.com/_kseki"

[languages]
  [languages.ja.params]
    title = "Klog"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    fullWidthTheme = false
    centerTheme = true

    [languages.ja.params.logo]
      logoText = "> Klog"
      logoHomeLink = "/"

    [languages.ja.menu]
      [[languages.ja.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      #[[languages.ja.menu.main]]
      #  idenjatifier = "showcase"
      #  name = "Showcase"
      #  url = "/showcase"
